//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberToWords {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NumberToWordResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumberToWordResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NumberToWords.NumberToWordResources", typeof(NumberToWordResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milmillonésimas.
        /// </summary>
        internal static string billionths {
            get {
                return ResourceManager.GetString("billionths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to céntimos.
        /// </summary>
        internal static string cents {
            get {
                return ResourceManager.GetString("cents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ocho.
        /// </summary>
        internal static string eight {
            get {
                return ResourceManager.GetString("eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ochocientos.
        /// </summary>
        internal static string eight_hundred {
            get {
                return ResourceManager.GetString("eight_hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dieciocho.
        /// </summary>
        internal static string eighteen {
            get {
                return ResourceManager.GetString("eighteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ochenta.
        /// </summary>
        internal static string eighty {
            get {
                return ResourceManager.GetString("eighty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to once.
        /// </summary>
        internal static string eleven {
            get {
                return ResourceManager.GetString("eleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quince.
        /// </summary>
        internal static string fifteen {
            get {
                return ResourceManager.GetString("fifteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cincuenta.
        /// </summary>
        internal static string fifty {
            get {
                return ResourceManager.GetString("fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cinco.
        /// </summary>
        internal static string five {
            get {
                return ResourceManager.GetString("five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quinientos.
        /// </summary>
        internal static string five_hundred {
            get {
                return ResourceManager.GetString("five_hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cuarenta.
        /// </summary>
        internal static string forty {
            get {
                return ResourceManager.GetString("forty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cuatro.
        /// </summary>
        internal static string four {
            get {
                return ResourceManager.GetString("four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cuatrocientos.
        /// </summary>
        internal static string four_hundred {
            get {
                return ResourceManager.GetString("four_hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catorce.
        /// </summary>
        internal static string fourteen {
            get {
                return ResourceManager.GetString("fourteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cien.
        /// </summary>
        internal static string hundred {
            get {
                return ResourceManager.GetString("hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cienmillonésimas.
        /// </summary>
        internal static string hundred_millionths {
            get {
                return ResourceManager.GetString("hundred_millionths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cienmilésimas.
        /// </summary>
        internal static string hundred_thousandths {
            get {
                return ResourceManager.GetString("hundred_thousandths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millón.
        /// </summary>
        internal static string million {
            get {
                return ResourceManager.GetString("million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millones.
        /// </summary>
        internal static string millions {
            get {
                return ResourceManager.GetString("millions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millonésimas.
        /// </summary>
        internal static string millionths {
            get {
                return ResourceManager.GetString("millionths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nueve.
        /// </summary>
        internal static string nine {
            get {
                return ResourceManager.GetString("nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to novecientos.
        /// </summary>
        internal static string nine_hundred {
            get {
                return ResourceManager.GetString("nine_hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diecinueve.
        /// </summary>
        internal static string nineteen {
            get {
                return ResourceManager.GetString("nineteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noventa.
        /// </summary>
        internal static string ninety {
            get {
                return ResourceManager.GetString("ninety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uno.
        /// </summary>
        internal static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ciento.
        /// </summary>
        internal static string one_hundred {
            get {
                return ResourceManager.GetString("one_hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to un.
        /// </summary>
        internal static string one_noun {
            get {
                return ResourceManager.GetString("one_noun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siete.
        /// </summary>
        internal static string seven {
            get {
                return ResourceManager.GetString("seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setecientos.
        /// </summary>
        internal static string seven_hundred {
            get {
                return ResourceManager.GetString("seven_hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diecisiete.
        /// </summary>
        internal static string seventeen {
            get {
                return ResourceManager.GetString("seventeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to setenta.
        /// </summary>
        internal static string seventy {
            get {
                return ResourceManager.GetString("seventy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seis.
        /// </summary>
        internal static string six {
            get {
                return ResourceManager.GetString("six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seiscientos.
        /// </summary>
        internal static string six_hundred {
            get {
                return ResourceManager.GetString("six_hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dieciséis.
        /// </summary>
        internal static string sixteen {
            get {
                return ResourceManager.GetString("sixteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sesenta.
        /// </summary>
        internal static string sixty {
            get {
                return ResourceManager.GetString("sixty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diez.
        /// </summary>
        internal static string ten {
            get {
                return ResourceManager.GetString("ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diezmillonésimas.
        /// </summary>
        internal static string ten_millionths {
            get {
                return ResourceManager.GetString("ten_millionths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diezmilésimas.
        /// </summary>
        internal static string ten_thousandths {
            get {
                return ResourceManager.GetString("ten_thousandths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to décimas.
        /// </summary>
        internal static string tenths {
            get {
                return ResourceManager.GetString("tenths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trece.
        /// </summary>
        internal static string thirteen {
            get {
                return ResourceManager.GetString("thirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to treinta.
        /// </summary>
        internal static string thirty {
            get {
                return ResourceManager.GetString("thirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mil.
        /// </summary>
        internal static string thousand {
            get {
                return ResourceManager.GetString("thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milésimas.
        /// </summary>
        internal static string thousandths {
            get {
                return ResourceManager.GetString("thousandths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tres.
        /// </summary>
        internal static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trecientos.
        /// </summary>
        internal static string three_hundred {
            get {
                return ResourceManager.GetString("three_hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doce.
        /// </summary>
        internal static string twelve {
            get {
                return ResourceManager.GetString("twelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to veinte.
        /// </summary>
        internal static string twenty {
            get {
                return ResourceManager.GetString("twenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to veinti.
        /// </summary>
        internal static string twenty_and {
            get {
                return ResourceManager.GetString("twenty_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dos.
        /// </summary>
        internal static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doscientos.
        /// </summary>
        internal static string Two_Hundred {
            get {
                return ResourceManager.GetString("Two_Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to con.
        /// </summary>
        internal static string with {
            get {
                return ResourceManager.GetString("with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cero.
        /// </summary>
        internal static string zero {
            get {
                return ResourceManager.GetString("zero", resourceCulture);
            }
        }
    }
}
